language: node_js
branches:
  only:
    - 0.x
    - 55.x
node_js:
  - node
#  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npx jest --ci
