language: node_js
branches:
  only:
    - master
    - ejected
node_js:
  - node
#  - lts/*
cache:
  directories:
#    - ~/.npm
#    - .jest
before_script:
  - ls -al src/services
  - dsds
  - npm install -g npm@latest
script:
  - npm ci
  - npx jest --ci
