export const WorkoutActions = {
  CREATE_WORKOUT: 'CREATE_WORKOUT',
  DELETE_WORKOUT: 'DELETE_WORKOUT',
  UPDATE_WORKOUT: 'UPDATE_WORKOUT',
  SET_ACTIVE_WORKOUT: 'SET_ACTIVE_WORKOUT',
  ADD_EXERCISE: 'ADD_EXERCISE',
  ADD_SET: 'ADD_SET',
  UPDATE_SET: 'UPDATE_SET',
  REMOVE_SET: 'REMOVE_SET',
};
